Add support for scanning IPv6 targets
Tripwire/padcheck pull request #2
Opened 2019-05-10 17:05 UTC by dexxtreme

I found that I had a need to scan for this vulnerability, however I am in an environment that also has IPv6 systems that needed to be scanned. I've added some logic to handle IPv6 addresses in the following formats (I tested on the command line as well as in a file supplied via -hosts):

[2604:1380:4111:200::3]:443
[2604:1380:4111:200::3]
2604:1380:4111:200::3
ipv6.icanhazip.com:443
ipv6.icanhazip.com

Additionally, I've verified that the Go patch will also apply to the Go 1.11.10 source.

2019-05-17 19:44 UTC, bespokebob requested changes
Please run `go fmt` on your changes.

2019-05-17 19:47 UTC, bespokebob requested changes

2019-05-17 19:47 UTC, youngbob commented on padcheck.go
> +		x,y,z := net.SplitHostPort(hostname)
These variables need useful names (host, port, err)

2019-05-21 14:57 UTC, dexxtreme commented
Several formatting fixes added.

2019-05-22 16:51 UTC, bespokebob approved these changes

2021-04-23 18:17 UTC, merged